version: "3.8"

services:
  todolist-app:
    image: vishallokam/todolist-docker:latest
    container_name: todolist_app
    ports:
      - '3000:3000'
    environment:
      MONGODB_SERVER_URL: "mongoDB:27017"
      DB_USER: devUser
      DB_PASS: devUserPass
    depends_on:
      mongo-db:
        condition: service_healthy
    
  
  mongo-db:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    secrets:
      - mongo_root_username
      - mongo_root_password
    environment: 
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
    volumes: 
      - mymongodata:/data/db
      - type: bind
        source: ./mongo-entrypoint
        target: /docker-entrypoint-initdb.d/
    healthcheck: 
      test: echo 'db.runCommand({find:"todolistDB.devUser"}).ok' | mongosh --authenticationDatabase admin --host localhost -u superUser -p superUserPass admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  mymongodata:

secrets:
  mongo_root_username:
    file: ./secrets/mongo_root_username.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt