version: "3.2"

services:
  todolist-app:
    image: vishallokam/todolist-docker:latest
    container_name: todolist_app
    ports:
      - '3000:3000'
    environment:
      MONGODB_SERVER_URL: "mongoDB:27017"
      DB_USER: devUser
      DB_PASS: devUserPass
  
  mongo-db:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: superUser
      MONGO_INITDB_ROOT_PASSWORD: superUserPass
    volumes: 
      - mymongodata:/data/db
      - type: bind
        source: ./mongo-entrypoint
        target: /docker-entrypoint-initdb.d/
    command: [--auth]

volumes:
  mymongodata:
